apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
data:
  BACKEND_URL: "https://back.misterdevops.xyz:80"  # Just the backend service name and port (default port 80)
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: akesosk.azurecr.io/akeso/frontend-dev:202502060116  # Replace with your frontend Docker image
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: frontend-config  # Referencing the ConfigMap to get the BACKEND_URL
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
      imagePullSecrets:
        - name: acr-registry2  # Use the created Docker registry secret for private images


---


apiVersion: v1
kind: Service
metadata:
  name: frontend-svc
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
